### ISSUE TITLE
Close button not working in settings

### ISSUE THREAD

**Issue by privatewanderer** [paichiwo/tube-getter#1]
Hi,

I've noticed that when you open the settings to change download location, blue "Close" button is not working. You have to use the "x" in the top right corner.

**Comment by paichiwo** [comment]
thank you for pointing it out, however at my end it works fine: 
https://github.com/paichiwo/tube-getter/assets/37277099/d9258caf-bd8f-41ac-8dea-4b6fcd30eeaf
so the question is which app version are you using and which os? I want to identify that issue and create a fix asap

**Comment by privatewanderer** [comment]
Hey,

Using v 1.2.1 on windows 10 Pro 22H2.
![image](https://github.com/paichiwo/tube-getter/assets/54600159/1e193703-6b57-49d8-960d-70be83704735)

Also, not sure what does the button right next to settings button, does nothing when I click it.
![image](https://github.com/paichiwo/tube-getter/assets/54600159/ecaf0b10-c1f8-4d3d-9e12-8cde7d712ca6)

**Comment by paichiwo** [comment]
please use the latest version 1.2.6 it uses new library that lets you download even age restricted videos and works much faster as well - https://github.com/paichiwo/tube-getter/releases/download/v1.2.6/Tube_Getter_v1.2.6.exe
The button next to the settings button should switch theme from light to dark and vice versa. However it doesn't work , I'm aware of it, Please let me know if the issue with close button still exists when using v1.2.6. I will work on it this week and v1.2.7 will be out  this weekend.

**Comment by privatewanderer** [comment]
I was misled by your readme file, it has the link to v1.2.1 version :) 
![image](https://github.com/paichiwo/tube-getter/assets/54600159/ea12896c-9b01-4857-8050-815f9f20ee8d)

On version 1.2.6 close button works! 
One thing though, I've downloaded 1.2.6 version, but in app itself it shows 1.2.5:
![image](https://github.com/paichiwo/tube-getter/assets/54600159/6664a2fd-b09a-4dbd-9c42-d52551203e03)

**Comment by paichiwo** [comment]
as promised i refactored the whole app and v1.2.7 is ready for use. As far as I know all the bugs have been fixed, and application should work much better. I've done some testing and everythings seems to be fine and working. 

![TG_screenshot_1](https://github.com/paichiwo/tube-getter/assets/37277099/2cff573f-89f3-4a85-a74e-3d2a6431f142)

https://github.com/paichiwo/tube-getter/releases/download/v1.2.7/Tube_Getter_v1.2.7.exe

Please let me know if you are happy to close this issue

**Comment by paichiwo** [comment]
https://github.com/paichiwo/tube-getter/releases/download/v1.2.9/Tube_Getter_v1.2.9.exe is out :)

**Comment by paichiwo** [comment]
v2.0 is out: https://github.com/paichiwo/tube-getter/releases/tag/v2.0_rc1
